username: 
password: 

positions:
- Software Developer
- .Net Software Developer
- # A third position you want to search for

locations:
- Australia
- United Kingdom
- Netherlands
- Canada

# --------- Optional Parameters -------
uploads:
 Resume: uploads/Delon_Savanhu_Resume_2022.pdf
 Cover Letter: /uploads/cover letter.pdf
#  Photo: # PATH TO photo


 output_filename:
 - uploads/output.csv

# blacklist:
# - # Company names you want to ignore

#blackListTitles:
#- # Add job titles you want to ignore
